
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine_polina
    username: postgres
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

opensearch:
  hostAndPort: localhost:9200